services:
  - type: web
    name: product_gallery
    env: python
    plan: free
    region: oregon
    branch: main
    workingDirectory: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput

    startCommand: |
      gunicorn product_gallery.wsgi:application --bind 0.0.0.0:8000 --workers 1

    healthCheckPath: /

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
    autoDeploy: true

